// app/api/clients/generate-post/route.ts

import { NextRequest, NextResponse } from 'next/server'
import Anthropic from '@anthropic-ai/sdk'
import { createServerSupabaseClient } from '@/lib/supabase-server'

const COST_PER_1K_INPUT_TOKENS = 0.003
const COST_PER_1K_OUTPUT_TOKENS = 0.015
const ESTIMATED_INPUT_TOKENS = 300
const ESTIMATED_OUTPUT_TOKENS = 200

export async function POST(request: NextRequest) {
  const supabase = await createServerSupabaseClient()

  try {
    // 1. AUTHENTICATION CHECK
    const { data: { user }, error: authError } = await supabase.auth.getUser()
    if (authError || !user) {
      return NextResponse.json({
        error: 'Unauthorized',
        details: 'Please log in to generate content'
      }, { status: 401 })
    }

    // 2. GET USER PROFILE
    const { data: profile } = await supabase
      .from('profiles')
      .select('test_mode, use_own_api_key, anthropic_api_key')
      .eq('id', user.id)
      .single()

    if (!profile) {
      return NextResponse.json({
        error: 'Profile not found',
        details: 'User profile could not be loaded'
      }, { status: 404 })
    }

    const isTestMode = profile.test_mode || false
    const useOwnKey = profile.use_own_api_key || false
    const userApiKey = profile.anthropic_api_key

    // 3. PARSE REQUEST BODY
    const body = await request.json()
    const {
      clientId,
      businessName,
      description,
      industry,
      tone,
      websiteUrl,
      facebookHandle,
      partnershipNotes,
      postTopic,
      eventDetails,
      wordCount,
      emojiLevel,
      additionalContext,
    } = body

    if (!businessName || !description) {
      return NextResponse.json(
        { error: 'Missing required fields: businessName and description' },
        { status: 400 }
      )
    }

    // 4. TEST MODE
    if (isTestMode) {
      await supabase.from('api_usage').insert({
        user_id: user.id,
        action: 'client_post_generate',
        count: 1,
        test_mode: true
      })

      return NextResponse.json({
        success: true,
        content: `[TEST MODE] Spotlight post for ${businessName}

This is mock content generated in TEST MODE. No credits were consumed.

Business: ${businessName}
Topic: ${postTopic}
Word Count: ~${wordCount} words
Emoji Level: ${emojiLevel}

To generate real content, disable Test Mode in your settings.`,
        tokensUsed: 0,
        cost: 0,
        testMode: true,
      })
    }

    // 5. DETERMINE API KEY
    let apiKey: string | undefined
    if (useOwnKey && userApiKey) {
      apiKey = userApiKey
    } else {
      apiKey = process.env.ANTHROPIC_API_KEY
    }

    if (!apiKey) {
      return NextResponse.json({
        error: 'No API key configured',
        details: 'Please add your Anthropic API key in settings or contact your administrator',
        action: 'configure_api_key'
      }, { status: 402 })
    }

    // 6. CHECK CREDIT BALANCE
    if (!useOwnKey) {
      const { data: creditData } = await supabase
        .from('credits')
        .select('balance')
        .eq('user_id', user.id)
        .single()

      const estimatedCost =
        (ESTIMATED_INPUT_TOKENS / 1000) * COST_PER_1K_INPUT_TOKENS +
        (ESTIMATED_OUTPUT_TOKENS / 1000) * COST_PER_1K_OUTPUT_TOKENS

      if (!creditData || creditData.balance < estimatedCost) {
        return NextResponse.json({
          error: 'Insufficient credits',
          details: `You need €${estimatedCost.toFixed(4)} to generate this post. Current balance: €${creditData?.balance.toFixed(4) || '0.0000'}`,
          action: 'purchase_credits',
          currentBalance: creditData?.balance || 0,
          requiredAmount: estimatedCost
        }, { status: 402 })
      }
    }

    // 7. BUILD PROMPT
    const prompt = buildClientPostPrompt({
      businessName,
      description,
      industry,
      tone,
      websiteUrl,
      facebookHandle,
      partnershipNotes,
      postTopic,
      eventDetails,
      wordCount,
      emojiLevel,
      additionalContext,
    })

    // 8. CALL CLAUDE API
    const anthropic = new Anthropic({ apiKey })

    let actualInputTokens = 0
    let actualOutputTokens = 0
    let generatedContent = ''

    try {
      const message = await anthropic.messages.create({
        model: 'claude-sonnet-4-5',
        max_tokens: 2048,
        messages: [{ role: 'user', content: prompt }]
      })

      generatedContent = message.content[0].type === 'text'
        ? message.content[0].text
        : ''

      actualInputTokens = message.usage?.input_tokens || ESTIMATED_INPUT_TOKENS
      actualOutputTokens = message.usage?.output_tokens || ESTIMATED_OUTPUT_TOKENS

      if (!generatedContent) throw new Error('No content generated by AI')

    } catch (apiError) {
      await supabase.from('api_usage').insert({
        user_id: user.id,
        action: 'client_post_generate',
        count: 1,
        test_mode: false
      })
      throw apiError
    }

    // 9. CALCULATE ACTUAL COST
    const actualCost =
      (actualInputTokens / 1000) * COST_PER_1K_INPUT_TOKENS +
      (actualOutputTokens / 1000) * COST_PER_1K_OUTPUT_TOKENS

    // 10. DEDUCT CREDITS
    if (!useOwnKey) {
      const { data: currentCredits } = await supabase
        .from('credits')
        .select('balance')
        .eq('user_id', user.id)
        .single()

      const newBalance = (currentCredits?.balance || 0) - actualCost

      await supabase
        .from('credits')
        .update({
          balance: newBalance,
          updated_at: new Date().toISOString()
        })
        .eq('user_id', user.id)

      await supabase.from('credit_transactions').insert({
        user_id: user.id,
        transaction_type: 'usage',
        amount: -actualCost,
        balance_after: newBalance,
        description: `Client spotlight post - ${businessName} - ${actualInputTokens + actualOutputTokens} tokens`,
        metadata: {
          input_tokens: actualInputTokens,
          output_tokens: actualOutputTokens,
          endpoint: 'client_post_generate',
          business_name: businessName,
          client_id: clientId,
          post_topic: postTopic,
        }
      })
    }

    // 11. LOG API USAGE
    await supabase.from('api_usage').insert({
      user_id: user.id,
      action: 'client_post_generate',
      count: 1,
      test_mode: false
    })

    // 12. RETURN SUCCESS
    return NextResponse.json({
      success: true,
      content: generatedContent,
      tokensUsed: actualInputTokens + actualOutputTokens,
      cost: useOwnKey ? 0 : actualCost,
      testMode: false,
    })

  } catch (error) {
    console.error('Client Post Generation Error:', error)
    return NextResponse.json(
      {
        error: 'Failed to generate post',
        details: error instanceof Error ? error.message : 'Unknown error'
      },
      { status: 500 }
    )
  }
}

function buildClientPostPrompt(params: {
  businessName: string
  description: string
  industry?: string
  tone?: string
  websiteUrl?: string
  facebookHandle?: string
  partnershipNotes?: string
  postTopic?: string
  eventDetails?: string
  wordCount?: number
  emojiLevel?: string
  additionalContext?: string
}) {
  const {
    businessName,
    description,
    industry,
    tone = 'friendly',
    websiteUrl,
    facebookHandle,
    partnershipNotes,
    postTopic = 'general_spotlight',
    eventDetails,
    wordCount = 150,
    emojiLevel = 'few',
    additionalContext,
  } = params

  const emojiInstruction = {
    none: 'Use absolutely no emojis.',
    few: 'Use 1-2 emojis sparingly and only where they feel natural.',
    moderate: 'Use 3-5 emojis placed naturally throughout the post.',
    lots: 'Use 6 or more emojis generously throughout the post.',
  }[emojiLevel] || 'Use a few emojis.'

  const topicInstruction = {
    general_spotlight: `Write a spotlight post introducing and promoting ${businessName} to the European Living community. Highlight what makes this business special and why the community should know about them.`,
    special_event: `Write an engaging post about this upcoming special event: ${eventDetails}. Make it exciting and include all relevant details.`,
    seasonal: `Write a timely, seasonal post for ${businessName} that connects their business to the current season or upcoming holidays.`,
    partnership: `Write a post highlighting the partnership between ${businessName} and Used Car Guys (UCG). Explain how both businesses serve the American expat and military community in Europe, and how they complement each other.`,
  }[postTopic] || `Write a spotlight post about ${businessName}.`

  return `You are the social media manager for the European Living Facebook page, which serves American expats and military families living in Europe, particularly in Germany.

You are writing a SPOTLIGHT PARTNER post featuring a local business that has partnered with Used Car Guys (UCG).

BUSINESS DETAILS:
- Name: ${businessName}
- Industry: ${industry || 'General Business'}
- Description: ${description}
${partnershipNotes ? `- Partnership Context: ${partnershipNotes}` : ''}
${websiteUrl ? `- Website: ${websiteUrl}` : ''}
${facebookHandle ? `- Facebook: @${facebookHandle}` : ''}

POST INSTRUCTIONS:
- Topic: ${topicInstruction}
- Tone: ${tone} — write in a ${tone} voice throughout
- Length: Approximately ${wordCount} words
- Emojis: ${emojiInstruction}
- Audience: American expats and military families living in Europe
${additionalContext ? `- Additional context: ${additionalContext}` : ''}

REQUIREMENTS:
- Write as if posting on behalf of European Living, a community Facebook page
- Make it feel authentic and community-focused, not like an advertisement
- Include a clear call to action (visit website, follow their page, contact them, etc.)
${facebookHandle ? `- Mention @${facebookHandle} to tag them in the post` : ''}
${websiteUrl ? `- Include their website: ${websiteUrl}` : ''}
- Keep the UCG connection subtle unless the topic is specifically about the partnership
- Write ONLY the post content — no explanations, no "Here is the post:" preamble, just the post itself

Write the post now.`
}

export async function GET() {
  return NextResponse.json({
    status: 'Client Post Generation API',
    endpoint: '/api/clients/generate-post',
  })
}