// app/api/schedules/[id]/regenerate/route.ts

import { NextRequest, NextResponse } from 'next/server'
import { createClient } from '@supabase/supabase-js'
import Anthropic from '@anthropic-ai/sdk'

const anthropic = new Anthropic({
  apiKey: process.env.ANTHROPIC_API_KEY,
})

// Server-side Supabase client with service role key
const supabaseAdmin = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
)

export async function POST(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const { id } = await params

    // Validate API key exists
    if (!process.env.ANTHROPIC_API_KEY) {
      console.error('ANTHROPIC_API_KEY is not set')
      return NextResponse.json(
        { error: 'Configuration error: Anthropic API key is not configured' },
        { status: 500 }
      )
    }

    console.log('Regenerating content for schedule:', id)

    // Fetch the schedule with all related data
    const { data: schedule, error: fetchError } = await supabaseAdmin
      .from('post_schedules')
      .select(`
        id,
        user_id,
        group_id,
        post_type,
        target_audience,
        special_context,
        special_offer,
        vehicle_data,
        testimonial_data,
        scheduled_for,
        facebook_groups!inner(
          name,
          group_type,
          description,
          territory_id,
          territories(name)
        )
      `)
      .eq('id', id)
      .single()

    if (fetchError || !schedule) {
      console.error('Schedule not found:', fetchError)
      return NextResponse.json(
        { error: 'Schedule not found' },
        { status: 404 }
      )
    }

    // Fetch user profile for contact info
    const { data: profile } = await supabaseAdmin
      .from('profiles')
      .select('full_name, email, whatsapp')
      .eq('id', schedule.user_id)
      .single()

    // Extract Facebook group data
    const group = Array.isArray(schedule.facebook_groups) 
      ? schedule.facebook_groups[0] 
      : schedule.facebook_groups

    const territory = group.territories 
      ? (Array.isArray(group.territories) ? group.territories[0] : group.territories)
      : null

    console.log('Generating with data:', {
      groupName: group.name,
      territory: territory?.name,
      postType: schedule.post_type,
      userProfile: profile?.full_name
    })

    // Build the prompt using the same logic as /api/posts/generate
    const prompt = buildPrompt({
      groupName: group.name,
      groupType: group.group_type,
      territory: territory?.name || 'Unknown',
      groupDescription: group.description,
      postType: schedule.post_type || 'brand_awareness',
      specialOffer: schedule.special_offer,
      targetAudience: schedule.target_audience,
      additionalContext: schedule.special_context,
      vehicleData: schedule.vehicle_data,
      testimonialData: schedule.testimonial_data,
      userProfile: profile || undefined
    })

    console.log('Calling Claude API...')

    // Generate fresh content with Claude
    const message = await anthropic.messages.create({
      model: 'claude-sonnet-4-20250514',
      max_tokens: 4096,
      messages: [
        {
          role: 'user',
          content: prompt
        }
      ]
    })

    const generatedContent = message.content[0].type === 'text' 
      ? message.content[0].text 
      : ''

    if (!generatedContent) {
      throw new Error('No content generated by AI')
    }

    console.log('Content generated successfully, updating schedule...')

    // Update the schedule with new content
    const { error: updateError } = await supabaseAdmin
      .from('post_schedules')
      .update({
        generated_content: generatedContent,
        content_generated_at: new Date().toISOString(),
        status: 'content_ready',
        updated_at: new Date().toISOString()
      })
      .eq('id', id)

    if (updateError) {
      console.error('Error updating schedule:', updateError)
      throw updateError
    }

    console.log('Schedule updated successfully')

    return NextResponse.json({
      success: true,
      content: generatedContent,
      metadata: {
        scheduleId: id,
        groupName: group.name,
        territory: territory?.name,
        postType: schedule.post_type,
        model: 'claude-sonnet-4',
        timestamp: new Date().toISOString()
      }
    })

  } catch (error) {
    console.error('Regenerate Error:', error)
    return NextResponse.json(
      { 
        error: 'Failed to regenerate content', 
        details: error instanceof Error ? error.message : 'Unknown error'
      },
      { status: 500 }
    )
  }
}

// Prompt builder function - copied from /api/posts/generate/route.ts
function buildPrompt(params: {
  groupName: string
  groupType?: string
  territory: string
  groupDescription?: string
  postType: string
  specialOffer?: string
  targetAudience?: string
  additionalContext?: string
  vehicleData?: {
    make: string
    model: string
    year: string
    price?: string
    features?: string
    condition?: string
    mileage?: string
  }
  testimonialData?: {
    customerName?: string
    vehicle: string
    experience?: string
    location?: string
  }
  userProfile?: {
    full_name: string
    email?: string
    whatsapp?: string
  }
}) {
  const { 
    groupName, 
    groupType, 
    territory, 
    groupDescription, 
    postType, 
    specialOffer,
    targetAudience,
    additionalContext,
    vehicleData,
    testimonialData,
    userProfile
  } = params

  // Determine if this is Stuttgart Brand Awareness (needs Nick + Terry)
  const isStuttgartBrandAwareness = territory.toLowerCase().includes('stuttgart') && postType === 'brand_awareness'
  
  // Extract salesperson info from user profile
  const salesPerson = userProfile?.full_name || 'our team'
  const salesWhatsApp = userProfile?.whatsapp || ''
  const salesEmail = userProfile?.email || ''
  
  // Leadership team (Nick + Terry for Stuttgart Brand Awareness only)
  const nickMorley = {
    name: 'Nick Morley',
    whatsapp: '+49 172 712 9046'
  }
  const terryLombardi = {
    name: 'Terry Lombardi',  
    whatsapp: '+49 151 6522 7520',
    email: 'terry@usedcarguys.net'
  }

  let basePrompt = ''

  // BRAND AWARENESS POST
  if (postType === 'brand_awareness') {
    basePrompt = `You are writing a BRAND AWARENESS Facebook post for Used Car Guys (UCG), a car dealership serving US military personnel in Germany.

TARGET GROUP: ${groupName}
TERRITORY: ${territory}
${groupType ? `GROUP TYPE: ${groupType}` : ''}

⚠️ CRITICAL: This is a BRAND AWARENESS post - NOT a vehicle ad!

📏 LENGTH REQUIREMENT:
- MINIMUM 1,500 words (aim for 2,000-3,000+ words)
- This should be DETAILED and COMPREHENSIVE
- Multiple sections with clear breaks
- Tell stories, share events, build relationships

🎨 EMOJI REQUIREMENTS (EXTREMELY IMPORTANT):
- Use 50+ emojis throughout the ENTIRE post
- Every 1-2 sentences should have an emoji
- Common ones: 🚗 ✨ 😍 ❤️ 💙 💚 💪 ⭐ 🎯 🏆 🙌 🎉 👋 😊 🤗 🦥 🐻 🕺 💃 🎵 🔒 💰
- Don't hold back - the owner LOVES emojis!

📝 TONE & VOICE:
- Warm, personal, community-focused (NOT salesy!)
- Excited and confident about serving military families
- Like talking to friends and neighbors
- Enthusiastic and genuine
- Focus on RELATIONSHIPS first, cars second
- Share stories, events, community involvement

🎯 BRAND AWARENESS POST STRUCTURE - FOLLOW THIS EXACTLY:

1️⃣ OPENING (Warm Welcome):
"Welcome to Used Car Guys ${territory}! 🚗✨"
"We are more than a car dealership! We are part of YOUR Community. 😍😍"
"We are a place where fun abounds, community partnership is priority and memories are made. Cars are just what we do!"

2️⃣ RELATIONSHIP PHILOSOPHY:
Include a meaningful quote about relationships, community, or service. Example:
"To UCG ${territory} we believe in relationships with our community. This quote sums up what our relationship with YOU means to us:"
"Time is the currency of relationships. There is no way to invest in a relationship without investing your time! (Author unknown)."

3️⃣ COMMUNITY INVOLVEMENT SECTION:
"HERE'S HOW UCG ${territory.toUpperCase()} INVESTED IN YOUR COMMUNITY IN [CURRENT MONTH]! 😊🎉"

Share 5-8 specific stories/events:
- Community events hosted
- Classes or activities (dance, fitness, educational)
- Local business support
- Scholarship programs
- Fun mascot/character updates (like Stewie the sloth)
- Charitable activities
- Military family support

Each story should be 2-3 sentences with emojis. Be creative and heartfelt!

4️⃣ LOOKING AHEAD:
"I wonder what [NEXT MONTH] will hold? Follow us on Used Car Guys ${territory} and find out more about our upcoming events and don't forget to check out our outstanding inventory! 🚗🎯"

5️⃣ WHAT WE OFFER SECTION:
"We have soooo much to offer you. Check this out: 😊"
1. FREE Event Space for the USAG Community
2. We support the Home Based Businesses
3. The John S. Sweeney Memorial Scholarship only for the USAG
4. Check out the HBB Little Shops located here at UCG

6️⃣ VEHICLE INVENTORY TRANSITION:
"Looking for your next car? At Used Car Guys, we're proud to offer a wide selection of top-quality pre-owned vehicles at prices you'll love! 🚗💙"

7️⃣ WHY CHOOSE US:
"💡 Why Choose Us?"
✅ Quality Assurance – Every car undergoes a thorough inspection to ensure you're getting the very best.
✅ Diverse Inventory – Both U.S. and E.U. Spec vehicles, from sporty sedans to family-friendly SUVs, we have the perfect car to fit your needs.
✅ Guaranteed Buy Back Offer– Come back to us when you are ready to sell!
✅ Expert Guidance – Our friendly team${isStuttgartBrandAwareness ? `, featuring ${nickMorley.name} and ${terryLombardi.name},` : ''} are here to guide you every step of the way—no pressure, just support!
✅ Check Our Google Reviews - Nearly 200 five-star reviews from the USAG ${territory} community!

8️⃣ VISIT US SECTION:
"📍 Visit Us:"
"Stop by our ${territory} showroom at Robert-Bosch-Straße 6, 71101 Schönaich, and see why we're the trusted choice for used cars in the region.${territory.toLowerCase().includes('stuttgart') ? " We're just around the corner from Panzer Kaserne!" : ''} ✨"
"🌐 Website: www.usedcarguys.net"

9️⃣ MEET THE TEAM:
${isStuttgartBrandAwareness 
  ? `"Come on in and meet our "Good Guys"! ${terryLombardi.name} and ${nickMorley.name} are here to help you find your perfect vehicle. 🚗✨"`
  : `"Come on in and meet ${salesPerson} and the team! We're here to help you find your perfect vehicle. 🚗✨"`
}

🔟 CONTACT SECTION:
"📞 Contact:"
${isStuttgartBrandAwareness 
  ? `${terryLombardi.name}'s WhatsApp at ${terryLombardi.whatsapp}
${nickMorley.name}'s WhatsApp ${nickMorley.whatsapp}`
  : `${salesPerson}'s WhatsApp: ${salesWhatsApp}
${salesEmail ? `📧 Email: ${salesEmail}` : ''}`
}

1️⃣1️⃣ CLOSING CTA:
"👍 Don't forget to like our page to stay updated on the latest arrivals, exclusive offers, and more!"
"💚 Your next car is waiting for you at The Used Car Guys ${territory} Showroom. Come see us today!${territory.toLowerCase().includes('stuttgart') ? " Don't forget to ask us about our low priced auto insurance with AmericanAutoNation and our extended warranty program. 💙✨" : ' 🚗✨'}"

${targetAudience ? `\n🎯 TARGET AUDIENCE: ${targetAudience}` : ''}
${additionalContext ? `\n📝 ADDITIONAL CONTEXT: ${additionalContext}` : ''}

🎨 REMEMBER: 
- Use 50+ emojis throughout
- 1,500+ words minimum
- Be warm, personal, community-focused, excited, and confident
- Tell stories and build relationships
- This is about UCG being part of the community, not just selling cars!`
  }

  // VEHICLE SPOTLIGHT POST
  else if (postType === 'vehicle_spotlight' && vehicleData) {
    basePrompt = `You are writing a VEHICLE SPOTLIGHT Facebook post for Used Car Guys (UCG).

TARGET GROUP: ${groupName}
TERRITORY: ${territory}
${groupDescription ? `GROUP CONTEXT: ${groupDescription}` : ''}

VEHICLE DETAILS:
- Make/Model: ${vehicleData.year} ${vehicleData.make} ${vehicleData.model}
${vehicleData.price ? `- Price: ${vehicleData.price}` : '- Price: Contact for pricing'}
${vehicleData.mileage ? `- Mileage: ${vehicleData.mileage}` : ''}
- Condition: ${vehicleData.condition}
${vehicleData.features ? `- Features: ${vehicleData.features}` : ''}

📏 LENGTH: 800-1,200 words

🎨 EMOJI USAGE: 30-40 emojis throughout (🚗 ✨ 💙 🔥 ⚡ 💪 🎯 ⭐ 🙌 etc.)

📝 TONE: Enthusiastic, exciting, excited, confident, lots of exclamation points!

[Rest of vehicle spotlight structure...]`
  }

  // SPECIAL OFFER POST
  else if (postType === 'special_offer') {
    basePrompt = `You are writing a SPECIAL OFFER Facebook post for Used Car Guys (UCG).

TARGET GROUP: ${groupName}
TERRITORY: ${territory}
OFFER: ${specialOffer || 'Special military pricing available'}

📏 LENGTH: 600-900 words
🎨 EMOJI USAGE: 25-35 emojis
📝 TONE: Urgent, exciting, confident, create FOMO!

[Rest of special offer structure...]`
  }

  // COMMUNITY POST
  else if (postType === 'community') {
    basePrompt = `You are writing a COMMUNITY FOCUS Facebook post for Used Car Guys (UCG).

TARGET GROUP: ${groupName}
TERRITORY: ${territory}

📏 LENGTH: 800-1,200 words
🎨 EMOJI USAGE: 30-40 emojis
📝 TONE: Warm, appreciative, excited, confident, community-focused!

[Rest of community structure...]`
  }

  // TESTIMONIAL POST
  else if (postType === 'testimonial_style' && testimonialData) {
    basePrompt = `You are writing a CUSTOMER SUCCESS STORY Facebook post for Used Car Guys (UCG).

TARGET GROUP: ${groupName}
TERRITORY: ${territory}

CUSTOMER STORY:
- Customer: ${testimonialData.customerName || 'A military family'}
- Vehicle: ${testimonialData.vehicle}

📏 LENGTH: 600-800 words
🎨 EMOJI USAGE: 25-30 emojis
📝 TONE: Warm, celebratory, inspiring, excited, confident!

[Rest of testimonial structure...]`
  }

  // Add territory-specific context
  if (territory.toLowerCase().includes('stuttgart')) {
    basePrompt += `\n\n📍 STUTTGART CONTEXT:
- Mention Patch Barracks, Panzer Kaserne, or Kelley Barracks
- Reference the USAG Stuttgart community
- Note proximity: "right near Panzer Kaserne"
- Use "Stuttgart" naturally throughout`
  } else if (territory.toLowerCase().includes('ramstein') || territory.toLowerCase().includes('kmc')) {
    basePrompt += `\n\n📍 KMC/RAMSTEIN CONTEXT:
- Mention Ramstein Air Base
- Reference KMC (Kaiserslautern Military Community)
- Talk about airmen and Air Force families`
  }

  basePrompt += `\n\n🎨 FINAL REMINDERS:
- Use LOTS of emojis
- Be excited and confident!
- Keep it personal and warm
- Focus on serving military families

Generate the Facebook post now.`

  return basePrompt
}